baseURL = "https://x-hain.de"
title = "xHain hack+makespace"
canonifyurls = true
languageCode = "en-us"
defaultContentLanguage = "de"
DefaultContentLanguageInSubdir = true
MetaDataFormat = "yaml"

# Define the number of posts per page
paginate = 6

[permalinks]
  post = "/:year/:month/:slug/"

[params]
  author = "xHain hack+makespace"
  defaultKeywords = ["hackspace", "makerspace", "xhain"]
  email = "info@x-hain.de"
  latitude = "52.512815"
  longitude = "13.4493919"
  og_image = "/images/hero.jpg"

[Permalinks]
    articles = "/blog/:year/:month/:day/:title/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[markup.goldmark.renderer]
  unsafe= true


###### TRANSLATIONS ######

[languages]
[languages.de]
weight = 1
languageName = "Deutsch"
languageCode = "de"
calendarName = "Kalender"
contentDir = "content/de"
title = "xHain hack+makespace"
defaultDescription = "Hack- & Makespace im Herzen von Friedrichshain, Bastelstube für Technikinteressierte + Raum für Netzpolitisches"

[languages.en]
weight = 2
languageName = "English"
languageCode = "en"
calendarName = "Calendar"
contentDir = "content/en"
title = "xHain hack+makespace"
defaultDescription = "Hack and make space in the heart of Friedrichshain, tinkering room for people interested in technology + space for net politics."

[languages.de.params.info]
title = "Mehr informationen"

[languages.en.params.info]
title = "More information"

[languages.de.params.tools]
title = "Unsere tools"

[languages.en.params.tools]
title = "Our tools"

[languages.de.params.social]
title = "Wir sind auch auf"

[languages.en.params.social]
title = "Find us elsewhere"

[menu]

###### MAIN MENU ######

[[languages.de.menu.main]]
  weight = 1
  identifier = "about"
  name = "Vorbeikommen"
  url = "/#content"

[[languages.de.menu.main]]
  weight = 2
  identifier = "participate"
  name = "Mitmachen"
  url = "/participate"

[[languages.de.menu.main]]
  weight = 3
  identifier = "support"
  name = "Unterstützen"
  url = "/support"


[[languages.en.menu.main]]
  weight = 1
  identifier = "about"
  name = "Drop by"
  url = "/#content"

[[languages.en.menu.main]]
  weight = 2
  identifier = "participate"
  name = "Participate"
  url = "/participate"

[[languages.en.menu.main]]
  weight = 3
  identifier = "support"
  name = "Support"
  url = "/support"

###### TOOLS MENU ######

[[languages.de.menu.tools]]
  weight = 1
  identifier = "blog"
  name = "Blog"
  url = "/blog"

[[languages.de.menu.tools]]
  weight = 2
  identifier = "matrix"
  name = "Chat"
  url = "https://matrix.to/#/#xhain:x-hain.de"

[[languages.de.menu.tools]]
  weight = 3
  identifier = "wiki"
  name = "Wiki"
  url = "https://wiki.x-hain.de/"

[[languages.en.menu.tools]]
  weight = 1
  identifier = "blog"
  name = "Blog"
  url = "/blog"

[[languages.en.menu.tools]]
  weight = 2
  identifier = "matrix"
  name = "Chat"
  url = "https://matrix.to/#/#xhain:x-hain.de"

[[languages.en.menu.tools]]
  weight = 3
  identifier = "wiki"
  name = "Wiki"
  url = "https://wiki.x-hain.de/"

###### SOCIAL MENU ######

[[languages.de.menu.social]]
  weight = 1
  identifier = "fediverse"
  name = "Fediverse"
  url = "https://chaos.social/@xHain_hackspace"

[[languages.de.menu.social]]
  weight = 2
  identifier = "github"
  name = "Github"
  url = "https://github.com/xHain-hackspace/"

[[languages.en.menu.social]]
  weight = 1
  identifier = "fediverse"
  name = "Fediverse"
  url = "https://chaos.social/@xHain_hackspace"

[[languages.en.menu.social]]
  weight = 2
  identifier = "github"
  name = "Github"
  url = "https://github.com/xHain-hackspace/"


###### FOOTER MENU ######

[[languages.de.menu.footer]]
  weight = 1
  identifier = "contact"
  name = "Kontakt"
  url = "/contact"

[[languages.de.menu.footer]]
  weight = 2
  identifier = "privacy"
  name = "Datenschutz"
  url = "/privacy"

[[languages.en.menu.footer]]
  weight = 1
  identifier = "contact"
  name = "Contact"
  url = "/contact"

[[languages.en.menu.footer]]
  weight = 2
  identifier = "privacy"
  name = "Privacy"
  url = "/privacy"
