name: Build & Deploy

on:
  push:
    branches:
      - github_ci

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.154.2"
          extended: true

      - name: Check Hugo
        run: |
          hugo env

      - name: Build
        run: |
          sudo ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
          hugo version
          hugo -d public_html --config config.toml,home.toml --cleanDestinationDir

      - name: Deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rlzvc -i --delete"
          SOURCE: "public_html/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /public

      # - name: Deploy
      #   uses: burnett01/rsync-deployments@v8
      #   with:
      #     switches: -avzr --delete
      #     path: public_html
      #     remote_path: /public
      #     remote_host: x-hain.de
      #     remote_port: 22
      #     remote_user: ${{ secrets.DEPLOY_USER }}
      #     remote_key: ${{ secrets.DEPLOY_KEY }}
