name: Hourly Build and Deploy

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes for testing

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: main

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
    secrets: inherit
